/*
 *   This file will be regenerated by `mulle-match-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_C_HEADERS_FILE DISABLE
 *
 *   To not let mulle-match-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_RUN DISABLE
 */
#ifndef _mulle__c__string__escape__provide_h__
#define _mulle__c__string__escape__provide_h__


#include "mulle-c-string-escape-version.h"


#endif
